// src/mocks/mockData.ts

export const mockReviews = [
  {
    id: 1,
    user_id: 2,
    nickname: '티몬과품바',
    title: '내돈내산 사용 후기 올린다',
    content:
      '이 사이트 타로점 정말 잘맞네요. 제가 받은 타로 결과가 현실과 너무 비슷해서 놀랐어요. 특히 연애운 부분에서 정확도가 높았습니다.',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-06-10',
    updated_at: '2024-11-17',
    view_count: 1240,
  },
  {
    id: 2,
    user_id: 3,
    nickname: '행운의토끼발',
    title: '타로 상담 받고 인생이 바뀌었어요',
    content: '처음에는 반신반의했는데, 타로 상담 받은 후 제 삶의 방향을 찾았어요. 정말 감사합니다.',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-12-13',
    updated_at: null,
    view_count: 8,
  },
  {
    id: 3,
    user_id: 4,
    nickname: '별빛타로',
    title: '직장운 타로 결과 공유합니다',
    content:
      '이직을 고민하던 중에 직장운 타로를 받아봤어요. 결과를 바탕으로 결정을 내렸는데 정말 잘한 것 같아요.',
    on_main: false,
    img_url: 'https://kr.object.ncloudstorage.com/example-bucket/review-images/review3.jpg',
    created_at: '2024-02-20',
    updated_at: null,
    view_count: 15,
  },
  {
    id: 4,
    user_id: 5,
    nickname: '운세마스터',
    title: '연애운 타로, 놀라운 정확도!',
    content: '연애운 타로를 받아본 결과, 정말 현재 제 상황과 너무 일치해서 깜짝 놀랐어요.',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-02-09',
    updated_at: '2024-11-20',
    view_count: 20,
  },
  {
    id: 5,
    user_id: 6,
    nickname: '타로의신',
    title: '재물운 타로 후기입니다',
    content:
      '재물운 타로를 받아보고 재테크 방향을 잡았어요. 몇 달 지났는데 벌써 효과가 나타나고 있어요.',
    on_main: false,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2025-01-28',
    updated_at: null,
    view_count: 128,
  },
  {
    id: 6,
    user_id: 2,
    nickname: '티몬과품바',
    title: '내돈내산 사용 후기 올린다',
    content: '이 사이트 타로점 정말 잘맞네요. 제가 받은 타로 결과가 현실과 너무 비슷해서 놀랐어요.',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-01-04',
    updated_at: '2024-02-14',
    view_count: 112,
  },
  {
    id: 7,
    user_id: 3,
    nickname: '행운의토끼발',
    title: '타로 상담 받고 인생이 바뀌었어요',
    content: '처음에는 반신반의했는데, 타로 상담 받은 후 제 삶의 방향을 찾았어요.',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-08-19',
    updated_at: null,
    view_count: 81,
  },
  {
    id: 8,
    user_id: 4,
    nickname: '별빛타로',
    title: '직장운 타로 결과 공유합니다',
    content: '이직을 고민하던 중에 직장운 타로를 받아봤어요.',
    on_main: false,
    img_url: 'https://kr.object.ncloudstorage.com/example-bucket/review-images/review3.jpg',
    created_at: '2024-06-11',
    updated_at: '2025-01-27',
    view_count: 105,
  },
  {
    id: 9,
    user_id: 5,
    nickname: '운세마스터',
    title: '연애운 타로, 놀라운 정확도!',
    content: '연애운 타로를 받아본 결과, 정말 현재 제 상황과 너무 일치해서 깜짝 놀랐어요.',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-04-05',
    updated_at: null,
    view_count: 120,
  },
  {
    id: 10,
    user_id: 6,
    nickname: '타로의신',
    title: '재물운 타로 후기입니다',
    content: '재물운 타로를 받아보고 재테크 방향을 잡았어요.',
    on_main: false,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-09-16',
    updated_at: null,
    view_count: 128,
  },
];
