export const mockReviews = [
  {
    id: 1,
    user_id: 2,
    chatlog_id: 1,
    nickname: '티몬과품바',
    title: '내돈내산 사용 후기 올린다',
    content:
      '이 사이트 타로점 정말 잘 맞네요. 처음에는 반신반의했지만, 실제로 점을 본 후 너무 놀랐어요. 제가 고민하고 있던 문제에 대한 해답을 정확하게 짚어주었고, 특히 연애운 부분에서의 해석이 정말 정확해서 감탄했습니다. 상담을 통해 제가 현재 처한 상황과 미래의 가능성에 대한 인사이트를 얻을 수 있었어요. 또한, 타로 카드의 의미를 하나하나 설명해 주셔서 신뢰가 갔고, 단순한 점괘가 아니라 심리적인 안정감까지 얻을 수 있었습니다. 앞으로도 종종 이용할 계획입니다!',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-06-10',
    updated_at: '2024-11-17',
    view_count: 1240,
  },
  {
    id: 2,
    user_id: 3,
    chatlog_id: 2,
    nickname: '행운의토끼발',
    title: '타로 상담 받고 인생이 바뀌었어요',
    content:
      '처음에는 반신반의했는데, 타로 상담을 받은 후 제 삶의 방향을 찾았어요. 그동안 여러 가지 고민이 많았고, 선택의 기로에서 갈팡질팡하고 있었는데 상담을 통해 생각이 정리되었어요. 특히 커리어와 인간관계에 대한 조언이 큰 도움이 되었고, 조심해야 할 부분까지 세세하게 알려주셔서 실생활에서 활용할 수 있었습니다. 상담 후에는 오히려 마음이 편안해지고, 긍정적인 방향으로 나아갈 수 있게 되어 너무 감사한 경험이었어요.',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-12-13',
    updated_at: null,
    view_count: 8,
  },
  {
    id: 3,
    user_id: 4,
    chatlog_id: 3,
    nickname: '별빛타로',
    title: '직장운 타로 결과 공유합니다',
    content:
      '이직을 고민하던 중에 직장운 타로를 받아봤어요. 그동안 현재 직장에서의 미래에 대해 확신이 없었고, 다른 곳으로 이동하는 것이 옳은 선택인지 고민이 많았는데 타로 상담을 통해 방향을 찾을 수 있었습니다. 상담사가 제 상황을 이해하고 공감하며 조언을 해줘서 마음이 한결 가벼워졌어요. 타로 카드에서 나온 직장운 흐름과 실제 현실에서 마주한 기회들이 너무 비슷해서 깜짝 놀랐습니다. 덕분에 자신 있게 새로운 도전을 할 수 있었습니다!',
    on_main: false,
    img_url: 'https://kr.object.ncloudstorage.com/example-bucket/review-images/review3.jpg',
    created_at: '2024-02-20',
    updated_at: null,
    view_count: 15,
  },
  {
    id: 4,
    user_id: 5,
    chatlog_id: 4,
    nickname: '운세마스터',
    title: '연애운 타로, 놀라운 정확도!',
    content:
      '연애운 타로를 받아본 결과, 정말 현재 제 상황과 너무 일치해서 깜짝 놀랐어요. 사실 최근 연애 문제로 고민이 많았는데, 타로 카드에서 제가 겪고 있는 문제를 정확하게 짚어주더라고요. 그리고 조언해주신 대로 행동을 해봤더니 관계가 훨씬 좋아졌어요. 타로가 단순한 운세 예측이 아니라, 제 자신을 되돌아보고 더 나은 방향으로 나아가게 도와주는 도구라는 걸 알게 되었습니다. 정말 유익한 경험이었어요.',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-02-09',
    updated_at: '2024-11-20',
    view_count: 20,
  },
  {
    id: 5,
    user_id: 5,
    chatlog_id: 5,
    nickname: '운세마스터',
    title: '연애운 타로, 놀라운 정확도!',
    content:
      '연애운 타로를 받아본 결과, 정말 현재 제 상황과 너무 일치해서 깜짝 놀랐어요. 사실 최근 연애 문제로 고민이 많았는데, 타로 카드에서 제가 겪고 있는 문제를 정확하게 짚어주더라고요. 그리고 조언해주신 대로 행동을 해봤더니 관계가 훨씬 좋아졌어요. 타로가 단순한 운세 예측이 아니라, 제 자신을 되돌아보고 더 나은 방향으로 나아가게 도와주는 도구라는 걸 알게 되었습니다. 정말 유익한 경험이었어요.',
    on_main: true,
    img_url: 'https://blog.kakaocdn.net/dn/bxapSC/btsIBVJnAdm/tDIQASFAMh5AzitaECGVK0/img.jpg',
    created_at: '2024-02-09',
    updated_at: '2024-11-20',
    view_count: 20,
  },
];
